name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MOZ_HEADLESS: "1"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Unit Tests
      working-directory: src
      run: |
        python manage.py test lists
    - name: Run Functional Tests
      working-directory: src
      run: |
        apt update -y && apt install -y firefox-esr
        pip install selenium
        python manage.py test functional_tests
    - name: Archive errors
      uses: actions/upload-artifact@v4
      with:
        name: screendumps
        path: src/functional_tests/screendumps/

        
